spring:
  application:
    name: matajo
  profiles:
    active: dev,aws
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
      enabled: true

server:
  tomcat:
    max-swallow-size: -1
    max-http-form-post-size: 50MB