spring:
  application:
    name: matajo
  profiles:
    active: local
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
      enabled: true

server:
  tomcat:
    max-swallow-size: -1
    max-http-form-post-size: 50MB